name: "Setup Anchor"
description: "Setup Anchor by installing, downloading, and adding it to the path."
author: "Aursen"
branding:
  icon: "play-circle"
  color: "green"
inputs:
  solana-cli-version:
    description: "The Solana CLI version"
    required: true
  anchor-cli-version:
    description: "The Anchor CLI version"
    required: true
  node-version:
    description: "The Node.js version"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    # maybe cache
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - uses: actions/cache@v3
      name: Cache Solana Tool Suite
      id: cache-solana
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-${{ runner.os }}-v${{ inputs.solana-cli-version }}
    - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ inputs.solana-cli-version }}/install)"
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      shell: bash
    - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
    - run: solana-keygen new --no-bip39-passphrase
      shell: bash
    - run: solana config set --url localhost
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    # maybe cache
    - run: corepack enable
      shell: bash
    - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
      shell: bash
    - uses: actions/cache@v3
      name: Cache Cargo registry + index
      id: cache-anchor
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: cargo-${{ runner.os }}-anchor-v${{ inputs.anchor-cli-version }}
    - run: cargo install --git https://github.com/project-serum/anchor --tag v${{ inputs.anchor-cli-version }} anchor-cli --locked --force
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      shell: bash
    - run: npm i -g typescript
      shell: bash
