name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          solana-cli-version: "1.10.32"
          anchor-cli-version: "0.25.0"
          node-version: "18.12.0"
      - run: anchor --version
      - run: solana --version
